<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ExpenseRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = [
            'date' => 'required|date|date_format:Y-m-d',
            'expense_item_id' => 'required|numeric|exists:expense_items,id',
            'amount' => 'required|numeric',
            'created_by' => 'nullable|numeric|exists:admins,id',
            'notes' => 'nullable|string',
        ];

        if ($this->method() == 'PUT') {
            $rules = [
                'date' => 'required|date|date_format:Y-m-d',
                'expense_item_id' => 'required|numeric|exists:expense_items,id',
                'amount' => 'required|numeric',
                'created_by' => 'nullable|numeric|exists:admins,id',
                'notes' => 'nullable|string',
            ];
        }
        return $rules;
    }

    public function validated()
    {
        $data = parent::validated(); // TODO: Change the autogenerated stub
        $data['created_by'] = auth()->id();
        return $data;
    }
}
