<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Str;

class InventoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = [
            'date' => 'required|date',
            'code' => 'nullable|string',
            'created_by' => 'nullable|numeric|exists:admins,id',
            'products' => 'required|array',
            'notes' => 'nullable|string',
        ];

//        if ($this->method() == 'PUT') {
//            $rules = [
//                'date' => 'required|date|date_format:Y-m-d',
//                'code' => 'nullable|string',
//                'created_by' => 'nullable|numeric|exists:admins,id',
//                'products' => 'required|array',
//            ];
//        }
        return $rules;
    }

    public function validated()
    {
        $data = parent::validated(); // TODO: Change the autogenerated stub
        $data['created_by'] = auth()->id();
        $data['code'] =  rand(100,99999);
        return $data;
    }

}
