<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class SupplierRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = [
            'name' => 'required|string|max:100|unique:suppliers,name',
            'phone' => 'required|numeric|unique:suppliers,phone',
            'is_active' => 'boolean',
            'area' => 'nullable|string',
            'address' => 'nullable|string',
            'notes' => 'nullable|string',
            'created_by' => 'nullable|numeric|exists:admins,id',
            'product_id' => 'nullable|array|exists:products,id',
        ];

        if ($this->method() == 'PUT') {
            $rules = [
                'name' => 'required|string|max:100|unique:suppliers,name,'. $this->supplier->id,
                'phone' => 'required|numeric|unique:suppliers,phone,' . $this->supplier->id,
                'is_active' => 'boolean',
                'area' => 'nullable|string',
                'address' => 'nullable|string',
                'notes' => 'nullable|string',
            ];
        }
        return $rules;
    }

    public function validated()
    {
        $data = parent::validated(); // TODO: Change the autogenerated stub
        $data['created_by'] = auth()->id();
        return $data;
    }
}
