<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UnitRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = [
            'name' => 'required|string|max:255',
            'is_active' => 'boolean',
            'created_by' => 'nullable|numeric|exists:admins,id',
        ];

        if ($this->method() == 'PUT') {
            $rules = [
                'name' => 'required|string|max:255',
                'is_active' => 'boolean',
            ];
        }
        return $rules;
    }

    public function validated()
    {
        $data = parent::validated(); // TODO: Change the autogenerated stub
        $data['created_by'] = auth()->id();
        return $data;
    }
}
